apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-vault
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.31.0
      helm:
        valueFiles:
          - $infra-repo/k8s_gitops/app/vault/resources/values.yaml
    # Source pour les ressources auxiliaires (namespace, secrets, etc.)
    - repoURL: https://github.com/jbwittner/infrastructure
      targetRevision: main
      ref: infra-repo
      path: k8s_gitops/app/vault/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: vault