# File: k8s_gitops/app/authentik/resources/postgres.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vault-db
  # No namespace needed here, ArgoCD will apply the destination namespace (authentik)
spec:
  instances: 3
  
  # Low resource profile for standard usage
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 1Gi

  storage:
    size: 10Gi
    storageClass: longhorn 

  bootstrap:
    initdb:
      database: vault
      owner: vault
      # This ensures the generated secret uses these specific keys if needed, 
      # but standard CNPG secrets (username/password) are fine for Authentik.