apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    application-type: infra
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # Source pour le chart Helm
    - chart: external-dns
      repoURL: https://kubernetes-sigs.github.io/external-dns
      targetRevision: 1.19.0
      helm:
        valueFiles:
          - $infra-repo/k8s_gitops/cluster_talos_ovh/infra/external-dns/resources/values.yaml
      # Source pour les ressources auxiliaires (namespace, secrets, etc.)
    - repoURL: https://github.com/jbwittner/infrastructure
      targetRevision: main
      ref: infra-repo
      path: k8s_gitops/cluster_talos_ovh/infra/external-dns/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
