apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-longhorn
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.10.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        valueFiles:
          - $infra-repo/k8s_gitops/cluster_talos_ovh/infra/longhorn/resources/values.yaml
      # Source pour les ressources auxiliaires (namespace, secrets, etc.)
    - repoURL: https://github.com/jbwittner/infrastructure
      targetRevision: main
      ref: infra-repo
      path: k8s_gitops/cluster_talos_ovh/infra/longhorn/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
