---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgCg3ubKwbhb+e0gT4+TdXbu/pj7H3doXaLsAmae6IGVHeQEWFZvz6DKrE3urutPUYvjOcIZ5SdzEQ1dk6ssqUk5hCv/UrZZG8U9BXfzokIzqPyJh1E4G/VJ7gvjMV7/wIt56En3EZN/fP7jwRr/7nVzjySYKjHa2VnS+DnsuEazSZ3IELVE2kTigV0GUn1JEGcZ8f7NohCcala0w37xdrgdo8pKppeAaLVGSiwiEGG288uh8CSNQ9wFxGhmo9HsstxJp5VqMMD6u+ptVOECgv653QfBkiMqLjaYmPNvA1hwcyV/zFIVmyLsz90N6t1tT7+xourpyE36Jqa8uFZzAFq34S+G7X/NaX8NxbiBWZrFelloyn5r57iIY5DHHTm3iisyBAXaXMJNHO5W84qjqE6qlLYd62EmWpzVHWKcCNvI0w6G/znLFV5XwdH3MVxH2bQj1xePJW5Rvcc7qJlg4cKL8TOvNXUuSUJpxDeOtZNEFXEOFWYeybifkboZA0Z6P6XErvUpPSs81zm8GAggEIVVmxcqkHabQIqmQ/JhTR0R9Qo0JeyOssvbCY8bURjKX7n1zEstNMJA9eKL2BpJyjKF9TVDIhazP1YAfPcga2SufYlWC6Y++nl5Rc2WGDQbo5FkybtQL+byhLoBHgODEQWYIJlrm1x0yC8J46anSHK8z+3RMa6ScubFGFHrkdUOobDhgZUl2C8A9yJgv+KFC+7axOW3TdRfrRyJC7eWPA/ymaa6h2dtLX9/Ty69lxb62F6ZoFz+TEg7DCGL0EFiC6lirZcw4ut1FrNq3NoxLM1/8M+Gi4UpQOS0d1IrS96CzWjAgLjZIzQ8SV7UXE4TgYuA1/eFlVpb1qCOnsHqpB84zXggYupXFNt3j3Vor9QO+UrCfMlA5QkWvMpIeLvJCqyztLpo5vPcal1WjEQXAONwC5QwvC8QTm6b
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel
