---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgAnpLXUBnsN9WPwPcbEOF5DDGBGCbEzkdfKawxeR7bM9lzB7rD7I/CMxxIkL4ifS1cyln/nFtVvyjPPLc+9BFAAwTjH94ByU4dzmaoYMhN/50ZLgw8sHBLJ3PH8LawCXpGkjyimuMqvwib47z4CrfUDN2PfCBgdHeatYopOcIDNNdG+1iMeSGN3eesZthoWOijk8PfQNYA7MVZbzZiuWg1j70YR0yLUHTpl0LLjb29itPbkaWhuEcoXdfpM9Xjwml5me0jVuAa2SMcb6rdfwQHGuYVDIfohwczcSTzWUn2vG+4n+i75vKvswmNnEF7JpZK/uAln9c+Gn6sRZdVIBI/VwzKHen1jUgVhTFHbv8zYs/v69mJ5VYprkEBSOpqXKYsc1c57mRQ5izaI2+wqHYux2ysmu1A7Ki0uY7KHZHAOBp12XOOEtj4mmWkmaxzcZ4EFeYyMlmLH+kOD+6KY6kSeeqGEKNrZYMhWYSX58I55JNIS0hex58uqUC3t1Ku//pbX9HByRt6+j8w6rYWqrwiC/R/PQIS1hB9mRZII12Pf0LojGC5r44rJtdW/FGNFMBtAAvdNdUkSCVSuBqu8Q9mD6C9SLsblJXzEFTwEO1nkmjJDZ1JFXAMBd46AV6UmD6RExk9BGNXAvCgbsnYmquQErLCd91+8FBM+KisUx3AqVFNF3SY6yoFXEt6vFz/VZIcBzXWWHmw+hQzT+kq5mFIrjUuTwPU3Buwe1J3P/WRvH/RoI69UH9XIxKGf0j9wPrYs8qalhDQ1gQoBt99cFbnu4NlIZmHjdkxOLY5yuok9sgNnBxSKy7ve9lnSCPjb5/vImd1K/zV9d9rWOIzZ8F2vvZi/2W3diyc7Vp3ayj2ztRXx1uolpqiG4Bskfpy89675X+nYRoVYO1EaYwpNqWyUwrw5WtABzwhnG28P8+jC+k2l8npLA/hk
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel
