---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgBgKjD+AdouM/YATHZuSuzCg0/WcbQMAKeXD5EGEGPDoeWc1DAqVGv74oKPqJuk+R7aKU/xyjuLjW3a66SmBF/ODUP83WC6YE76sjeslrnzMeIGDxnHdR8bcnN2tAUXrE5FCaXdlcL7uIEkUwLECtyHPGczbDlEBj5W6k/Id32rJ16zgTWv+oTGoqtfp71y6ViDzsskftswuOZHvEWCkn5YjS5n2pbVdVFhQk7GtIN6Ff2dMKbCDYeLKvEwmtcN8yxNUkatn8SlIIOwLtvOPjEMvMceJo5GeLuZLHoIrBYY/f8wjfWpZM7eqPTc9ocd9VDrdKXT/a9+WGRdVaZrxTamwGzJ5IofOkrVZjubBkcIJ0qvkkqopwRmifFfBJI6125Wo4hnDu2FOny1vzuUQkIrDXOKGG6vEg5Vj1EE85dXN4/q48XcYEZA0U/2zKDPaFMzGc01uZbfVMkIGxNGrHwbGFEoqiqqljRvUoYw+JX45APdwhdWoiA7rqjJuVdB660gBu4NRJVcQm2b5f7trCo2eIC1qbPuSq+KefPci0P4EKNNkEwxda8ISqW0UdiYe1P+77z7r7ytbCEKUzS5tP6cLPfpxEdGXrUp8x5wu7et4JJAOyz83ubgc3OZhwz3F407bmwMJitQNI7XMyf1VVu4t7orVxtsgNvA5M+CdbKUf0Dcvq8YfR0S9kC25YL6fU5PELRg1sIc8R0qniApv+BodSox/NdlXjgnL+V6Fe0=
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel
