apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-longhorn
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.10.1 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        values: |
          persistence:
            defaultClassReplicaCount: 1
          metrics:
            serviceMonitor.enabled: true
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            # CRITICAL FOR NETWORK ISSUES + REPLICA 1:
            # "strict-local" forces the volume to be on the same node as the pod.
            # If the pod moves, Longhorn will try to migrate the data (heavy network usage)
            # or block startup if it can't.
            # "best-effort" is safer: it prefers local, but allows remote if disk is full.
            defaultDataLocality: best-effort
            # DISABLE auto-balancing to save network bandwidth.
            # Since you have network issues, you don't want Longhorn moving 
            # gigabytes of data just to balance disk usage automatically.
            replicaAutoBalance: disabled
      # Source pour les ressources auxiliaires (namespace, secrets, etc.)
    - repoURL: https://github.com/jbwittner/infrastructure
      targetRevision: main
      path: k8s_gitops/infra/longhorn/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
