---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    apiKey: AgCQyb6q+NrUz4ExwO009/QJGGNzWk4Hnl80q4OMUOgFuCwOTDa4HW6VCaVGh6e5cZxSlqrgaXeMNnHyHfMfiaQIKUg8V1o7/a9+8EEz8BoWEl+iJviB/LA+8jGMY4NI06gNboAc8n9ClM/gJt09wVHc9XPQcdSbJfsfw/sa9dfsmgCSbekUgQKXszEZdTHDerOT2zZq7HviPb332X6OszNoZ2AxToTuDQAkuF8T+NBDYJ63nNOgJU4ARkda2YxiUNGj40wfyVdFiCyDe3dIayDGmje05RcF6oXmYBeAImqRihJA6XOKleweCc5L4Vp3P63iEZnOv6WXvPn/9MsUhSD0lIyBzjfvosBr8GXdbZxI0942WwmurQ2VNg2TFPue42QegjqZj8cYzVzkUX9H5pKJO4c5PQQl5xsYFWvftw7LZ4pjYyc/6GoNUdEYkCKh3vZquDHIIMGosbaDIkrVPXT6rTN5xhxvLquK3R0oUWT3os0PKjdEwhklDgw7RtfDwben1kC6ByIWiYRQ3nwhjbtNT6P7bhdVm8pEMJtbJKqhbpjmHORUUmPql4nr4fFzkNpcgU+oTFNlGkFZW1XU7amBywklQpDVA3lTolmdoP7H9AQHvaGB4BnCjzSm0iW77cRN4HNttrt9/qhUhCYH2ra8EgfQDOZnBxmcZrHJM08+oxkfqLMYCP7TNFNqsdIKPb+AyXTHUTPO+/fyowJzcGWCrW3ULuW6xGsKdDMhEnqnyOEA4QFGCNKE
    email: AgCoVM51scwkZYfj7bGQbFgrReOPh0QITxreNmOq6ZS80zmxBw+yzDR9QBG0zdqCQcoPWDAk7F++QuWsVYWfGm0ykDUu3oKv10Gi7QQJ8dM1uxua3fqI8aRa86kX4GuNBVzW9YlWSbyM6vwAlu9V6DfnpomtTEAytQPbEdkuqzP9fBA8Qxk0y6GLV0us5le2MkA/IDBVDdAUVhhjEQy8I7ccWzEg2qTLvndpPJmAhaTsuII9PMUOfCOJ79D/lJJNKchOLuIIS93us01y8SvUKjumzWkVJ/BCDT+/ke/qwyZQLEBdXRiTOhkO0NsQflF2USajr705m8CSYLrUYjQoLFM4Zx1mTdSpwAaCSLBpHdXWNlhtIAvQkGqOKiDvsZ7TYn4MWZ2RTKTOBzqXB10T3MZrAiukY0kUJCdMJkOVP1IBL0Q8r/EN6v2n6+tZLT8OnnrRAAHJj5C92c6FXWtdwia86KN9RokFPje57a22XTzPgmY8zVYM+zlJ9ucfoe8tqnZuVbKsS8AsJbG0or2hvviY4fHuIKvirjCLQLoD+F7Oigzr6PnDUi+er0i9jLgxPIAhem6hSnmt7dZEeyFwbmF/b45athxhh1h2+y8esa20B6BbVnMi9z4PG69jeVnE2jvVQWq4yLkJOyVIJ90yHi8JHELrvZ3tqMK6ICwDhUICx9p2wkjK0BeGS+L+nbhF4EnlNJAAo5K258B7TfvQsvXjleF5ShKh61cSq18HVBPbnQ==
  template:
    metadata:
      name: cloudflare-api-key
      namespace: external-dns
