---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    apiKey: AgC6HkUfO7r1kWxjyXimnErVufCKYxFm/lq1T9Wt/EIQS5pmoJjKKqNvyUyppJomSJ8HC4vbObBSo69eO/OrmC3/fqAbrCvh8FViKQ2KSFE/4IX7BXeDXV1VN+pwJHVG5FjjtEdpbAmvpEFSzSMzI+bqkK/hHetNPBAME1xc8vGj8gAx5ITzyC4q29er1x9JqRojTAPX/RzIS1kADKcQH4213KGVzzEjSFlYMYHsPWZMkWF7D1Ftj//2AcYuGlaj3OMFb2KFQ1N8GaaxoYl4hBhOZCNBQlWzlr0I8PpZ9pWAfBDR3BJVciYwCiU+zi+TCF6qMu3LqAeEVhsCQL7+kcDdNquVfI++YTm51wH3Qc8liSwy9LY5W0vzhIfqR4TS7tGN7qXBjp0kyzguQhxwY+SC+ilGBMgAEND5LN3UuMOVTY/kX9qKvfOEz8Gz3uk9TRDB53yl764DjiDc1ZsUhFwQ69+BBtmwxG+qLp3bjduqAQO57n5QPbyd5YsqVlj58ess1wIRTtVoYg+kAYR1I/mJeS8aAxDni6rpLlCZEktqc27iAla8FoW5Z4Ll8UTW0umWKaLNgZNOr1MdrcNn8wHs0gY7/XNOcCgRYtRa2KbkOtrm7iQIm9NuvOlpsgA2H1CJb6Bp4IX2Khf/QzpVNmlVq0a3bizmjFSrxhPhovoQ9sVejoNQGi1cgrLGDY2ASEtQDjQC89mwSmoRupnlYpP9BP0+xWeRlit9SfKASkgm8YMhog1mE6kp
    email: AgA1NA6yeoNrKwLEsXeHPZR8DwEQLRFsMsLWpL/V4/k2Wvsp79dm3ekfwFn2F0Zyk6g7mzwgrA1oAy3oZ4tKX/gsIJHY9dWz9KxpTkb0g6kjrncF9akJFGhWMSnBcJYsFlmCR3Yia4P5zbvwd1/y60qW9eLnpVSPf0oFb1d+Fm2mLcMQpvPxR7LpISAZpcn073F7DwbH6Efj5VbBb7e+wu6ESD8fcRKYje3mg6cc2nfIYOG2/CL33C8dGC96MWtqhod2KxB8cU8kEljtNL6kkNjurflacfSwQJjw0JrSzkfT9Q9Spkcwl41aSBKbP+dstEtxplvVgWWWucRykhaQNwtV8fzAi27qN+pxth/Ipc1t+rZpelPiXBhJmiGdU4fACQBKsZLUi+oW4TOUO4cYNOMB2dG1RiTaxxL8I7TOzLyoDNl/FnSTsUXMw6fofQuo3KQg6uwg3tldyHhvo+bb/oZ835lcd8dHeLuSxO8n8yfW/4M0J01Us0juVpK5HKgiycG7JMfL7aSgwTZamuBHbLwzvlfvLxJ8DY9wlkJ7yS+NCWAHgfYrYw5dv/bXLHHFkl4clVfLObiPJqKixOrYzB112owOftaxyj7s4VZPgeaN+k0Sc40Kx6FwEq4v8vishHExb+FR5x+wcgmT+8Cs3LrfWpcUKAGdasEuv22Ozgo9cbTRUlMN0hxDGp50yFWnLBvzq9IiYItDfyJJKimx9Rb5AuiDxSlxLHrP2pCCdRm/bw==
  template:
    metadata:
      name: cloudflare-api-key
      namespace: external-dns
