---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-key
  namespace: external-dns
spec:
  encryptedData:
    apiKey: AgDFRcrLDacp6baVjL0uKxqRqyamKwbK5qC8dfGCUar31Ec+a8ho9MONjYG/PPboE3w+maOv7Tl6jC9aRGQExMVW/W4376hqEAOh5UPw8ND+6OoprkqTjiQ8h5aCNJSXSikMtboTWPkPHN0lp2lSUD7pu88uWOaUYJg+3LWm+qcsakGum5kw/WxMVFJlq67jKCdsM6nFYVz7j9jJGevRMb3cjc/hg2wCNZgOljmj2sgqTTLziDw3epjCBcWD8M8oA8j1f+FG7nuHqu2pmO7JzsvFtxmPruxVseNMB/MPcBdMGeDuqd8ZAujihdJAWo2wa/70OlGTM0nO7PWoM5K2MwMlD6QF0VQwo5HzxbPqpbzmFZzKigbnMRHaoaavi1o3/pTuh4gIwCeLW8vE/+V84lv2UrgGRwqOriAtoXJXit898aSdZZOukisnjNRoYVU5bQTdII96+tx2ABnKu1VRMgI9IWnTQ1mrDur2zX0yB2IqBD69Gj9dX8gWNQ+nM1xFRc87truuip/ZghL2ZTTe7ZArmNDt6Og9nIlwsrF2vA4YcVNN7AMpuv+paNVrKl2uC+RozjoGVZuD+6llDahWGBHBHTWC0nBgr2Fn8AdUu9HMHxKJw2PhOSZ2m22e3611GGCBooz81OpQfng2Oiccz4d7+zvUCSjyedjC5FZkBx+KE0OSwxV8Ju4uBH0OFL4YkGqS8Bb/2LLir7njQSrQKWEQJon+8PqbM8cbfWEREaYZXbafOlO+pEuH
    email: AgBXdN7/w3isZQg0ZRMxg+v18DUYQXnr9wh10xEgJYSnpqPKr4ORUdgDaVwMVnDiBtALc7Dd7GPqtLjF7QMl6nd0XtNDDfrNFYyjEev6TS1LSCbp2Q+CPXaKDXDUeRD2RSErD6qB/g1EeOHDblAplZjuf/aQnnqdlntitvQWBLPlGkSCs3LucSROadahPginNdMz8oOefJmUPSeo0BCQJ/nIp1pyVHTQFRlgiiEoY+1pAyJ1f0tmKJqT7ypBQs3w2WT5qa+eiNiFo5euLkb4UiWIpkj0+yi5jhsc+jOp8TxOIS/ZIQJLvtHb96vfvB4vSxV3ElxSpfoHK1x0uqVD/gT4Oia0AVTGFsP+LNlO5h0y+jdT4gBYJFp7dfIxQg0aGQKYs9qb8VTdKsysSEwI+Pk6jrraoJSmeJBk6hLO92N+ApEamYOPShdyNYxt96Y7Z2/TUSxS7UjKgYiryo2dQ4PORz+nBPLk/rTz0di4tEVHDDuLkE6DI41dCm8UFi1eq4pobXBNguCAH47KRSTFczmbo0F1idJj8QKm3To05mY25NT11dP0BIiG18UrAo1fZMqt7RbQqzgL2lJ3A7e1mRPYaRNDRmhn3qLBqmr7ialvTb84I+ispYbsKMGolXonnSMJUuXYyIoXWLE+9oiA+ktRwrGoN86iSO5/SBn1tX0cHWQsQ5yD5BTrRR+3ccNUQZ6kCB3FqQR6Wq2BKq4+GQ8RQ1es/At73Rdu9o14SsNkrA==
  template:
    metadata:
      name: cloudflare-api-key
      namespace: external-dns
