apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-tunnel-wittnerlab-com-test
  namespace: argocd
  labels:
    application-type: infra
spec:
  project: default
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    # Source pour le chart Helm
    - chart: cloudflare-tunnel
      repoURL: https://cloudflare.github.io/helm-charts
      targetRevision: 0.3.2
      helm:
        values: |
          cloudflare:
            tunnelName: wittnerlabcom-tunnel-kubernetes
            tunnelId: ffdf68d9-6878-4a0e-88c1-6877ff5630e6
            secretName: cloudflare-tunnel-token
            ingress:
              - hostname: "*.wittnerlab.com"
                service: "https://infra-ingress-nginx-controller.ingress-nginx.svc.cluster.local:443"
                originRequest:
                  noTLSVerify: true
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          replicaCount: 2
    # Source pour les ressources auxiliaires (namespace, secrets, etc.
    - repoURL: https://github.com/jbwittner/infrastructure
      targetRevision: main
      path: k8s_gitops/cluster_talos_ovh/infra/cloudflare-tunnel/tunnel-helm/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-tunnel-test
