---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgAsvufHNGsqG8zbdRCdNQxGl1iY/Cws3UNQxuWK81FWBWJHvmckhx17hxTcW/nv1ABH0TF814yi7OUBni3YME8i4JJACwXNrpntyAWbktXJKGl8mi/IIqpcqnjDKAlCnPk5UgcfCwngUw7TVuWJRsex4OSp59lBouflerBa9plTjrSsWDIAhmnHNrEjPscueP2lmsl7GgxcHlyrMUBCqolB0lBUwQEQafvnEJXm7ICh2YEb99ZbD6yiV4lRj1uKNrkWOQ8LKtCuQ4e+fUxDGpkFVZ7aN5UQJnzQ2KgzoyAXwC6TkJKVYk1roJ7YAf1lEsoF1SacVGfZRgF5LjWOw7dMY5u/1EqWKGA74t2rZfR639VwIG093o75hDrvPLY1mRnnTQNxzAnoj9GloSxBu/gUT5T9tGVgnSvk+5IFjiwzsBSrjHMlGxpVlevM4U5cFlxgdoKgPcCXQQ11FFUyeSgwY4Flb2be7h2dWy7+0TqT4Y33vnH/VJ1AJvL9jYGzG9G5QN8zg3N44G0YBYi/81UIs8g7lrgHS0afQgiz2Z+iqJrRspIlert4J3lPwhAsjWoEHFV7iHLc5EggBULY2KYfL7Evs9Cp0j5z6IqT9W7hTmvcP54vsdXC4eMRGpWZ4fYgtB6pzCm6tcR7ClFf1Peoj6g5vunTrteLIjbWFU2m6lCc2ikyJaOOOcw3OtXFbEfsT7ez1yZ/hJLUTFHZQnVovkBIypj/71fTmWLKxEOIUaFS5JpAW69RSXYTubWVy7Ig+QerdydA6TA84Jm21216t5gekKga28BPm669ubVAd9Wzyb3ynHZ72YO0vks9s1beXtEqGNIzEXdBsu9Cz5UbbCaNVyD9quGw1aLMEQiJJzmBP8OK8rvl85qA34QhrADW0piXOaYNgC5J4amJTYf8FTyE7KSuqfvicCeehu1kw6G4HCGucgG2
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel