apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: podmonitor-cloudnative-pg-cluster
  labels:
    release: app-monitoring
spec:
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: cnpg.io/cluster
        operator: Exists
  podMetricsEndpoints:
  - port: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: podmonitor-cloudnative-pg-operator
  labels:
    release: app-monitoring
spec:
  namespaceSelector:
    matchNames:
      - cnpg-system
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
  - port: metrics
