apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-monitoring
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  sources:
    # Source pour le chart Helm
    - chart: kube-prometheus-stack
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 79.11.0
      helm:
        valueFiles:
          - $infra-repo/k8s_gitops/app/monitoring/resources/values.yaml
    - repoURL: https://github.com/jbwittner/infrastructure
      targetRevision: main
      ref: infra-repo
      path: k8s_gitops/app/monitoring/resources
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
