services:
  squash: # Must match the service name in the original file
    env_file:
      - example.env
    ports:
      - 8080

  postgresql: # Must match the service name in the original file
    env_file:
      - example.env
